#!/usr/bin/env bash

process () {
    tail -n+2 "$1" | sed -n '/^--- failing/q;p'
}

n=1
c=$(($(process tests.csv | wc -l)))

printf "1..%d\n" "$c"

process tests.csv | \
(fail=0
while IFS=, read -r description args input expected
do
    output=$(../bcalc $args <<<"$input" 2>&1)
    if [ "$description" == "" ] || [ "$output" != "$expected" ]; then
        printf "not ok %d - %s\n" "$n" "$description"
        printf "#\n#    got '%s', expected '%s'\n#\n" "$output" "$expected"
        fail=1
    else
        printf "ok %d - %s\n" "$n" "$description"
    fi
    n=$((n + 1))
done
 exit $fail
)

